/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sivecoProject1;

/**
 *
 * @author PC
 */

import java.io.*;
import java.util.*;
import java.text.SimpleDateFormat;


public class IdentificationCardGUI extends javax.swing.JFrame {

    /**
     * Creates new form IdentificationCardGUI
     */
    
    // Variables to store the input that the user typed in the Fields
    
    
    public static IdentificationCardINFO Objectformfile = null;
    public static String inputNume;
    public static String inputPrenume;
    public static String inputCetatenie;
    public static String inputLocNastere;
    public static int inputCNP;
    public static String inputDataNasterii;
    public static String inputSeria;
    public static int inputNr;
    public static String inputAdresa;
    public static String inputRandomNumber;
    public static String StringFinalData;
    public static String currentTime;
    public static String inputValabilitate;
    public static Integer randomNumber;
    
    
    public static IdentificationCardINFO DefaultObject = new IdentificationCardINFO("DefaultNume", "DefaultPrenume","DefaultCetatenie",
                                                                                    "DefaultLocNastere","DefaultAdresa",100000000,
                                                                                    "DefaultDataNasterrii", "DefaultSeria",1234,"DefaultRandomNumber",
                                                                                    "DefaultValabilitate");
    
    public IdentificationCardGUI() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NumeField = new javax.swing.JTextField();
        PrenumeField = new javax.swing.JTextField();
        CetatienieOptionsField = new javax.swing.JComboBox<>();
        LocNastereField = new javax.swing.JTextField();
        AdresaField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RandomNumberAutoField = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SeriaField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SavaButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ValabilitateNowField = new javax.swing.JLabel();
        NrField = new javax.swing.JSpinner();
        CNPField = new javax.swing.JSpinner();
        DataComboField = new datechooser.beans.DateChooserCombo();
        ValabilitateFinalField = new javax.swing.JLabel();
        ErrorField = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Carte de identitate");

        jLabel2.setText("CNP");

        jLabel3.setText("NUME");

        jLabel4.setText("PRENUME");

        jLabel5.setText("CETATENIE");

        jLabel6.setText("LOC NASTERE");

        jLabel7.setText("ADRESA");

        jLabel8.setText("DATA NASTERII");

        NumeField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                NumeFieldInputMethodTextChanged(evt);
            }
        });
        NumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeFieldActionPerformed(evt);
            }
        });

        PrenumeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenumeFieldActionPerformed(evt);
            }
        });

        CetatienieOptionsField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romania", "Germania", "Italia", "Franta" }));
        CetatienieOptionsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetatienieOptionsFieldActionPerformed(evt);
            }
        });

        LocNastereField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocNastereFieldActionPerformed(evt);
            }
        });

        AdresaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresaFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("RANDOM NUMBER");

        RandomNumberAutoField.setText("Generat automat : random+CNP");

        jLabel11.setText("SERIA");

        jLabel12.setText("NR");

        SavaButton.setText("SAVE");
        SavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavaButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("VALABILITATE");

        ValabilitateNowField.setText("Today->today + 7 ani");

        ErrorField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        this.SeriaField.setText(Objectformfile.seria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(AdresaField)
                                                .addComponent(LocNastereField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PrenumeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(NumeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(CetatienieOptionsField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(CNPField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(114, 114, 114)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(NrField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                    .addComponent(SeriaField)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(ValabilitateFinalField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(ValabilitateNowField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(SavaButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(CancelButton))
                                            .addComponent(ErrorField)))
                                    .addComponent(DataComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(RandomNumberAutoField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(SeriaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(NrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PrenumeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ValabilitateNowField))
                .addGap(4, 4, 4)
                .addComponent(ValabilitateFinalField)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(CetatienieOptionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SavaButton)
                        .addComponent(CancelButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LocNastereField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ErrorField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdresaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(DataComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(RandomNumberAutoField))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        this.NumeField.setText(Objectformfile.nume);
        this.PrenumeField.setText(Objectformfile.prenume);
        this.LocNastereField.setText(Objectformfile.locNastere);
        this.AdresaField.setText(Objectformfile.adresa);
        this.RandomNumberAutoField.setText(Objectformfile.randomNumber);
        this.ValabilitateNowField.setText(Objectformfile.valabilitate);
        this.NrField.setValue(Objectformfile.nr);
        this.CNPField.setValue(Objectformfile.CNP);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void checkdefault(String a){
        if(a.equals("")){
            a = "Errors: ";
        }
        
    }
    
    private void SavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavaButtonActionPerformed
        
        boolean status = true;
        
        inputNume = NumeField.getText();
        inputPrenume = PrenumeField.getText();
        inputCNP = (Integer) CNPField.getValue();
        inputNr = (Integer) NrField.getValue();
        inputSeria = SeriaField.getText();
        inputLocNastere = LocNastereField.getText();
        inputCetatenie=  String.valueOf(CetatienieOptionsField.getSelectedItem());
        inputAdresa = AdresaField.getText();
        
        this.ErrorField.setText("");
        
        //Check if the data introduced by the user in the fields is valid
        //If not, do NOT save and display an error message
        
        if(inputNume.length()<3){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "Nume invalid | ");
            System.out.println("\nError1");
        }
        if(inputPrenume.length()<3){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "Prenume invalid | ");
            System.out.println("\nError2");
        }
        if(inputCNP < 100000000){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "CNP invalid | ");
            System.out.println("\nError3");
        }
        if(inputNr < 1000){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "Nr invalid | ");
            System.out.println("\nError4");
        }
        if(inputSeria.length() != 2){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "Serie buletin invalida | ");
            System.out.println("\nError6");
        }
        if(inputLocNastere.length()< 3){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "Loc nastere invalid | ");
            System.out.println("\nError7");
        }
        
        if(inputAdresa.length()<3){
            status  = false;
            checkdefault(this.ErrorField.getText());
            this.ErrorField.setText(this.ErrorField.getText()+ "Adresa invalida | ");
            System.out.println("\nError8");
        }
        
        
        
        if (status == true){
            
            this.ErrorField.setText("No errors | "
                                    + "Operation succesfull");
            
            // Set the date format
            SimpleDateFormat format1 = new SimpleDateFormat("dd-MM-yyyy");

            // Set inputDataNasterii to the input in DataComboField
            Calendar myDate = DataComboField.getSelectedDate();
            inputDataNasterii = format1.format(myDate.getTime());

            // Get the current time
            Calendar current = Calendar.getInstance();
            currentTime  =  format1.format(current.getTime());

            // Set the final time (current time + 7 years)
            Calendar final_time = current;
            final_time.add(Calendar.YEAR, 7);
            StringFinalData =  format1.format(final_time.getTime());

            inputValabilitate = currentTime + " to " + StringFinalData; 

            //Change the labels ( ValabilitateNowField and ValabilitateFinalField) text with the new data
            this.ValabilitateNowField.setText("Starts: " + currentTime);
            this.ValabilitateFinalField.setText("Ends: " + StringFinalData);

            // Check if the CNP is the same with the one from the file
            // If it is, do NOT generate another random number;
            if(inputCNP == Objectformfile.CNP){
                inputRandomNumber = Objectformfile.randomNumber ;
                this.RandomNumberAutoField.setText(inputRandomNumber);
            }
            //Else, generate another random number for the new CNP
            else{
                int randomNumber = 100000 +  (int)(Math.random() * 999999);
                inputRandomNumber = String.valueOf(randomNumber) + ">>" + inputCNP ;
                String stringCNP = String.valueOf(inputCNP);
                this.RandomNumberAutoField.setText(inputRandomNumber);
            }



            // Create a new IdentificationCardINFO Object with the input set by the user

            IdentificationCardINFO IdentificationCardObject = new IdentificationCardINFO(
                                                              inputNume, 
                                                              inputPrenume,inputCetatenie,
                                                              inputLocNastere,inputAdresa,
                                                              inputCNP,inputDataNasterii,
                                                              inputSeria,inputNr,inputRandomNumber,inputValabilitate
                                                              );


            // Serializing the IdentificationCardObject
            try {
             File file = new File("C:\\Users\\PC\\Documents\\NetBeansProjects\\IdentificationCardRegister\\src\\sivecoProject1\\data.ser");
             FileOutputStream fileOut = new FileOutputStream(file);
             ObjectOutputStream out = new ObjectOutputStream(fileOut);
             out.writeObject(IdentificationCardObject);
             out.close();
             fileOut.close();
             System.out.printf("\n Serialized data is saved in data.ser\n");
            }catch(IOException i) {
             i.printStackTrace();
            }
            // Now the Object that is stored in the file is IdentificationCardObject

            Objectformfile = IdentificationCardObject;


            // Print out what is stored NOW (after the serialization) on the file

            System.out.println(" \nCNP : "+ IdentificationCardObject.CNP + " \nNume: " +
                               IdentificationCardObject.nume + " \nPrenume" + IdentificationCardObject.prenume+
                               " \nAdresa: " + IdentificationCardObject.adresa + " \nCetatenie: " + IdentificationCardObject.cetatenie+
                               " \nSeria: " + IdentificationCardObject.seria + " \nNr: "+ IdentificationCardObject.nr+
                               " \nLocNastere: " + IdentificationCardObject.locNastere + " \nrandomNumber: " + IdentificationCardObject.randomNumber
                                + " \nData Nasterii: " + IdentificationCardObject.dataNasterii + "\nValabilitate: " + Objectformfile.valabilitate
                               );

        }
        else{
            System.out.println("\nInvalid ");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_SavaButtonActionPerformed

    private void CetatienieOptionsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetatienieOptionsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CetatienieOptionsFieldActionPerformed

    private void AdresaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresaFieldActionPerformed

    private void PrenumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenumeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenumeFieldActionPerformed

    private void NumeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeFieldActionPerformed
        
    }//GEN-LAST:event_NumeFieldActionPerformed

    private void LocNastereFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocNastereFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocNastereFieldActionPerformed

    private void NumeFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_NumeFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeFieldInputMethodTextChanged

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);//Close the program
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentificationCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentificationCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentificationCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentificationCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        // Read the data.ser file and create a new object with the data(Objectformfile)
        try {
            
            File file = new File("C:\\Users\\PC\\Documents\\NetBeansProjects\\IdentificationCardRegister\\src\\sivecoProject1\\data.ser");
            
            //Create a new file if the data.ser does not exists
            if(!file.exists()){
                file.createNewFile(); 
                try {
                    FileOutputStream fileOut = new FileOutputStream(file);
                    ObjectOutputStream out = new ObjectOutputStream(fileOut);
                    out.writeObject(DefaultObject);
                    out.close();
                    fileOut.close();
                    System.out.printf("\n Serialized data is saved in the new data.ser\n");
                }catch(IOException i) {
                    i.printStackTrace();
                }
                
            }
            FileInputStream fileIn = new FileInputStream(file);
            ObjectInputStream in= new ObjectInputStream(fileIn);
            Objectformfile = (IdentificationCardINFO) in.readObject();
            System.out.printf(" Data extracted for data.ser ");
            in.close();  
        }catch(Exception i) {
            
         i.printStackTrace();
         
        }
        
        
        //Print the attributes of Objectformfile
        System.out.println(" \nCNP : "+ Objectformfile.CNP + " \nNume: " +
                           Objectformfile.nume + " \nPrenume: " + Objectformfile.prenume+
                           " \nAdresa: " + Objectformfile.adresa + " \nCetatenie: " + Objectformfile.cetatenie+
                           " \nSeria: " + Objectformfile.seria + " \nNr: "+ Objectformfile.nr+
                           " \nLocNastere: " + Objectformfile.locNastere + " \nrandomNumber: " + Objectformfile.randomNumber +
                           " \nData Nasterii: " + Objectformfile.dataNasterii + "\nValabilitate: " + Objectformfile.valabilitate);
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdentificationCardGUI().setVisible(true);
            }
        });
        
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresaField;
    private javax.swing.JSpinner CNPField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> CetatienieOptionsField;
    private datechooser.beans.DateChooserCombo DataComboField;
    private javax.swing.JLabel ErrorField;
    private javax.swing.JTextField LocNastereField;
    private javax.swing.JSpinner NrField;
    private javax.swing.JTextField NumeField;
    private javax.swing.JTextField PrenumeField;
    private javax.swing.JLabel RandomNumberAutoField;
    private javax.swing.JButton SavaButton;
    private javax.swing.JTextField SeriaField;
    private javax.swing.JLabel ValabilitateFinalField;
    private javax.swing.JLabel ValabilitateNowField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
